global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    env: local

scrape_configs:

  - job_name: "user-metadata-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-metadata-service:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: "deployment-portal"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["deployment-portal:8081"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
